language: 'generic'
services:
  - docker

before_install:
  - docker build -t $DOCKER_ID/fibonacci-app-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true $DOCKER_ID/fibonacci-app-client-test npm test

after_success:
  - docker build -t $DOCKER_ID/fibonacci-app-client ./client
  - docker build -t $DOCKER_ID/fibonacci-app-api ./api
  - docker build -t $DOCKER_ID/fibonacci-app-worker ./worker
  - docker build -t $DOCKER_ID/fibonacci-app-server ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/fibonacci-app-client
  - docker push $DOCKER_ID/fibonacci-app-api
  - docker push $DOCKER_ID/fibonacci-app-worker
  - docker push $DOCKER_ID/fibonacci-app-server
