version: '3'
services:
  client:
    image: 'emirhanaydin/fibonacci-app-client'
    deploy:
      resources:
        limits:
          memory: 128m
  api:
    image: 'emirhanaydin/fibonacci-app-api'
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: 'emirhanaydin/fibonacci-app-worker'
    deploy:
      resources:
        limits:
          memory: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  server:
    image: 'emirhanaydin/fibonacci-app-server'
    deploy:
      resources:
        limits:
          memory: 128m
    ports:
      - '80:80'
